name: COM3524

channels:
  - conda-forge

dependencies:
  - python=3.7.8
  - pip
  - pip:
    - numpy==1.19.2
    - Flask==2.2.2
    - matplotlib==3.3.1
    - eventlet==0.26.1
    - Flask_SocketIO==5.3.1
    - gunicorn==20.0.4

